language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release
    - PYTHON=2.7
    - PYTHON=3.6.7  #these might need to change over time

before_install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-key update; sudo apt-get update; fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./.travis/ubuntu.deps.sh; fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./.travis/osx.deps.sh; fi

script:
#  - mkdir -p build
#  - cd build
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib ..; fi
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..; fi
#  - make
#  - make check
   - ./.travis/check.sh