language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release
    - PYTHON=2.7
    - PYTHON=3.6.7

before_install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-key update; sudo apt-get update; fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./.travis/ubuntu.deps.sh; fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./.travis/osx.deps.sh; fi

script:
   - ./.travis/check.sh